import { UserCircleIcon, WrenchIcon, TruckIcon, ShoppingBagIcon, BuildingOfficeIcon, HomeIcon, CodeBracketIcon, BriefcaseIcon, UserGroupIcon } from '@heroicons/react/24/outline'
import { WrenchScrewdriverIcon, TruckIcon as TruckSolidIcon, ShoppingBagIcon as ShoppingSolidIcon, BuildingOfficeIcon as OfficeSolidIcon, HomeIcon as HomeSolidIcon, CodeBracketIcon as CodeSolidIcon, BriefcaseIcon as BriefcaseSolidIcon, UserGroupIcon as UsersSolidIcon } from '@heroicons/react/24/solid'

export const SERVICE_CATEGORIES = [
  { label: 'Electrician', value: 'Electrician', icon: WrenchScrewdriverIcon },
  { label: 'Plumber', value: 'Plumber', icon: WrenchIcon },
  { label: 'Carpenter', value: 'Carpenter', icon: WrenchIcon },
  { label: 'Mason', value: 'Mason', icon: BuildingOfficeIcon },
  { label: 'Painter', value: 'Painter', icon: WrenchIcon },
  { label: 'AC Repair', value: 'AC Repair', icon: WrenchScrewdriverIcon },
  { label: 'Washing Machine', value: 'Washing Machine Repair', icon: HomeIcon },
  { label: 'Refrigerator', value: 'Refrigerator Repair', icon: HomeIcon },
  { label: 'RO Purifier', value: 'RO Water Purifier Service', icon: WrenchIcon },
  { label: 'Home Cleaning', value: 'Home Cleaning', icon: HomeIcon },
  { label: 'Pest Control', value: 'Pest Control', icon: WrenchIcon },
  { label: 'Appliance Repair', value: 'Appliance Repair', icon: WrenchScrewdriverIcon },
  { label: 'Mobile Repair', value: 'Mobile Repair', icon: CodeBracketIcon },
  { label: 'Laptop Repair', value: 'Computer/Laptop Repair', icon: CodeBracketIcon },
  { label: 'Delivery Service', value: 'Delivery Services', icon: TruckIcon },
  { label: 'Driver Service', value: 'Driver Services', icon: TruckIcon },
  { label: 'Security Guard', value: 'Security Guard', icon: UserGroupIcon },
  { label: 'Housekeeping', value: 'Housekeeping', icon: HomeIcon },
  { label: 'Salon at Home', value: 'Salon at Home', icon: UserGroupIcon },
  { label: 'Tailor', value: 'Tailor Services', icon: ShoppingBagIcon },
]

export const dummyWorkers = [
  { id: 'w1', name: 'Rajesh Kumar', email: 'rajesh@example.com', phone: '+91 98765 43210', skills: ['Plumber', 'Pipe Fitting'], location: 'Lajpat Nagar, Delhi', bio: 'Experienced plumber with 8+ years. Specializing in residential and commercial plumbing solutions.', rating: 4.8, total_reviews: 124, experience_years: 8, completion_rate: 97, availability: true, lat: 28.5700, lng: 77.2400, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-blue-500' },
  { id: 'w2', name: 'Priya Singh', email: 'priya@example.com', phone: '+91 98765 43211', skills: ['Home Cleaning', 'Deep Cleaning', 'Office Cleaning'], location: 'Connaught Place, Delhi', bio: 'Professional cleaner providing spotless results. Eco-friendly products used.', rating: 4.9, total_reviews: 89, experience_years: 5, completion_rate: 99, availability: true, lat: 28.6315, lng: 77.2167, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-pink-500' },
  { id: 'w3', name: 'Amar Patel', email: 'amar@example.com', phone: '+91 98765 43212', skills: ['Electrician', 'Wiring', 'AC Repair'], location: 'Karol Bagh, Delhi', bio: 'Licensed electrician. Expert in wiring, switchboard installation, and AC servicing.', rating: 4.7, total_reviews: 156, experience_years: 10, completion_rate: 95, availability: true, lat: 28.6514, lng: 77.1907, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-yellow-500' },
  { id: 'w4', name: 'Sunita Devi', email: 'sunita@example.com', phone: '+91 98765 43213', skills: ['Painter', 'Wall Art', 'Texture Painting'], location: 'Rajouri Garden, Delhi', bio: 'Creative painter with modern techniques. Interior and exterior painting specialist.', rating: 4.6, total_reviews: 67, experience_years: 6, completion_rate: 93, availability: true, lat: 28.6492, lng: 77.1219, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-purple-500' },
  { id: 'w5', name: 'Vikram Choudhary', email: 'vikram@example.com', phone: '+91 98765 43214', skills: ['Carpenter', 'Furniture Repair', 'Wood Work'], location: 'Dwarka, Delhi', bio: 'Skilled carpenter specializing in custom furniture and repair work.', rating: 4.5, total_reviews: 98, experience_years: 12, completion_rate: 96, availability: true, lat: 28.5921, lng: 77.0460, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-orange-500' },
  { id: 'w6', name: 'Meena Kumari', email: 'meena@example.com', phone: '+91 98765 43215', skills: ['Housekeeping', 'Home Cleaning', 'Gardening'], location: 'Hauz Khas, Delhi', bio: 'Professional housekeeper. Deep cleaning, lawn maintenance, and indoor plant care.', rating: 4.8, total_reviews: 45, experience_years: 4, completion_rate: 98, availability: true, lat: 28.5494, lng: 77.2001, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-green-500' },
  { id: 'w7', name: 'Arjun Reddy', email: 'arjun@example.com', phone: '+91 98765 43216', skills: ['AC Repair', 'Refrigerator Repair', 'Appliance Repair'], location: 'Saket, Delhi', bio: 'Certified HVAC technician. All brands of AC, fridge, and cooling systems.', rating: 4.7, total_reviews: 112, experience_years: 7, completion_rate: 96, availability: true, lat: 28.5245, lng: 77.2066, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-cyan-500' },
  { id: 'w8', name: 'Fatima Khan', email: 'fatima@example.com', phone: '+91 98765 43217', skills: ['Salon at Home', 'Bridal Makeup', 'Hair Styling'], location: 'Khan Market, Delhi', bio: 'Professional beautician offering salon services at your doorstep. Bridal packages available.', rating: 4.9, total_reviews: 78, experience_years: 6, completion_rate: 99, availability: true, lat: 28.6003, lng: 77.2274, hourly_rate: 800, user_type: 'worker', avatar_color: 'bg-rose-500' },
  { id: 'w9', name: 'Suresh Yadav', email: 'suresh@example.com', phone: '+91 98765 43218', skills: ['Mason', 'Tile Work', 'Waterproofing'], location: 'Rohini, Delhi', bio: 'Expert mason with specialization in tile fitting, plastering, and waterproofing solutions.', rating: 4.4, total_reviews: 86, experience_years: 9, completion_rate: 92, availability: true, lat: 28.7495, lng: 77.0565, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-amber-600' },
  { id: 'w10', name: 'Kavitha Nair', email: 'kavitha@example.com', phone: '+91 98765 43219', skills: ['Pest Control', 'Termite Treatment', 'Fumigation'], location: 'Defence Colony, Delhi', bio: 'Licensed pest control specialist. Safe, eco-friendly treatments for homes and offices.', rating: 4.6, total_reviews: 54, experience_years: 5, completion_rate: 97, availability: true, lat: 28.5742, lng: 77.2340, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-lime-600' },
  { id: 'w11', name: 'Rohit Sharma', email: 'rohit@example.com', phone: '+91 98765 43220', skills: ['Mobile Repair', 'Screen Replacement', 'Software Fix'], location: 'Chandni Chowk, Delhi', bio: 'Mobile phone repair expert. All brands - Apple, Samsung, OnePlus, Xiaomi and more.', rating: 4.5, total_reviews: 132, experience_years: 4, completion_rate: 94, availability: true, lat: 28.6562, lng: 77.2302, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-indigo-500' },
  { id: 'w12', name: 'Deepak Mishra', email: 'deepak@example.com', phone: '+91 98765 43221', skills: ['Computer/Laptop Repair', 'Networking', 'Data Recovery'], location: 'Noida Sector 62', bio: 'IT hardware specialist. Laptop repair, OS installation, virus removal, and data recovery.', rating: 4.7, total_reviews: 91, experience_years: 8, completion_rate: 95, availability: true, lat: 28.6270, lng: 77.3653, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-violet-500' },
  { id: 'w13', name: 'Ramesh Gupta', email: 'ramesh@example.com', phone: '+91 98765 43222', skills: ['Driver Services', 'Outstation Trips', 'Airport Transfer'], location: 'Rajiv Chowk, Delhi', bio: 'Professional driver with commercial license. City rides, airport transfers, and outstation trips.', rating: 4.3, total_reviews: 64, experience_years: 10, completion_rate: 91, availability: true, lat: 28.6328, lng: 77.2197, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-teal-500' },
  { id: 'w14', name: 'Anita Joshi', email: 'anita@example.com', phone: '+91 98765 43223', skills: ['Tailor Services', 'Alterations', 'Custom Stitching'], location: 'Chittaranjan Park, Delhi', bio: 'Expert tailor for men and women. Blouse stitching, alterations, and custom outfits.', rating: 4.8, total_reviews: 76, experience_years: 10, completion_rate: 98, availability: true, lat: 28.5388, lng: 77.2479, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-fuchsia-500' },
  { id: 'w15', name: 'Manoj Tiwari', email: 'manoj@example.com', phone: '+91 98765 43224', skills: ['Washing Machine Repair', 'Appliance Repair'], location: 'Noida Sector 15', bio: 'Washing machine specialist - front load, top load, semi-automatic. All major brands.', rating: 4.4, total_reviews: 58, experience_years: 5, completion_rate: 93, availability: true, lat: 28.5836, lng: 77.3100, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-sky-500' },
  { id: 'w16', name: 'Sanjay Verma', email: 'sanjay@example.com', phone: '+91 98765 43225', skills: ['RO Water Purifier Service', 'Water Testing'], location: 'Barakhamba Road, Delhi', bio: 'RO purifier installation, repair, and annual maintenance. All brands serviced.', rating: 4.5, total_reviews: 42, experience_years: 3, completion_rate: 95, availability: true, lat: 28.6340, lng: 77.2280, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-blue-400' },
  { id: 'w17', name: 'Prakash Raj', email: 'prakash@example.com', phone: '+91 98765 43226', skills: ['Security Guard', 'CCTV Monitoring'], location: 'Gurgaon Cyber City', bio: 'Former military personnel. Professional security services for events, offices, and residences.', rating: 4.6, total_reviews: 38, experience_years: 8, completion_rate: 99, availability: true, lat: 28.4949, lng: 77.0882, hourly_rate: 300, user_type: 'worker', avatar_color: 'bg-slate-600' },
  { id: 'w18', name: 'Pooja Bansal', email: 'pooja@example.com', phone: '+91 98765 43227', skills: ['Delivery Services', 'Courier', 'Parcel Handling'], location: 'Golf Course Road, Gurgaon', bio: 'Reliable same-day delivery and courier services within Delhi NCR. Fragile items handled with care.', rating: 4.3, total_reviews: 49, experience_years: 2, completion_rate: 96, availability: true, lat: 28.4595, lng: 77.1025, hourly_rate: 250, user_type: 'worker', avatar_color: 'bg-orange-400' },
  { id: 'w19', name: 'Vijay Malhotra', email: 'vijay@example.com', phone: '+91 98765 43228', skills: ['Electrician', 'Generator Repair', 'Solar Installation'], location: 'Paharganj, Delhi', bio: 'Master electrician with expertise in generators and solar panel installation.', rating: 4.6, total_reviews: 72, experience_years: 12, completion_rate: 94, availability: true, lat: 28.6448, lng: 77.2165, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-red-500' },
  { id: 'w20', name: 'Neha Agarwal', email: 'neha@example.com', phone: '+91 98765 43229', skills: ['AC Repair', 'Ventilation', 'Air Quality'], location: 'Mayur Vihar, Delhi', bio: 'Specialized in central AC systems, air quality improvement, and ventilation solutions.', rating: 4.8, total_reviews: 58, experience_years: 6, completion_rate: 97, availability: true, lat: 28.5939, lng: 77.2978, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-emerald-500' },
  { id: 'w21', name: 'Gaurav Saxena', email: 'gaurav@example.com', phone: '+91 98765 43230', skills: ['Plumber', 'Bathroom Fitting', 'Sanitary'], location: 'Vasundhara, Ghaziabad', bio: 'Expert bathroom renovation and sanitary fitting specialist. All modern fixtures.', rating: 4.5, total_reviews: 83, experience_years: 7, completion_rate: 95, availability: true, lat: 28.5211, lng: 77.3855, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-sky-400' },
  { id: 'w22', name: 'Preeti Gupta', email: 'preeti@example.com', phone: '+91 98765 43231', skills: ['Salon at Home', 'Hair Coloring', 'Keratin Treatment'], location: 'Greater Kailash, Delhi', bio: 'Celebrity hairstylist offering advanced hair treatments at home.', rating: 4.9, total_reviews: 112, experience_years: 9, completion_rate: 99, availability: true, lat: 28.5436, lng: 77.2361, hourly_rate: 1200, user_type: 'worker', avatar_color: 'bg-pink-400' },
  { id: 'w23', name: 'Ravi Teja', email: 'ravi@example.com', phone: '+91 98765 43232', skills: ['Mobile Repair', 'Tablet Repair', 'Accessories'], location: 'Lajpat Nagar, Delhi', bio: 'Expert in smartphones, tablets, and all mobile accessories. Quick screen replacements.', rating: 4.4, total_reviews: 95, experience_years: 5, completion_rate: 92, availability: true, lat: 28.5667, lng: 77.2432, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-indigo-400' },
  { id: 'w24', name: 'Suman Lata', email: 'suman@example.com', phone: '+91 98765 43233', skills: ['Tailor Services', 'Designer Outfits', 'Bridal'], location: 'Shahdara, Delhi', bio: 'Master tailor specializing in bridal wear and designer ethnic outfits.', rating: 4.7, total_reviews: 64, experience_years: 15, completion_rate: 98, availability: true, lat: 28.6769, lng: 77.2927, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-rose-400' },
  { id: 'w25', name: 'Ajay Kumar', email: 'ajay@example.com', phone: '+91 98765 43234', skills: ['Pest Control', 'Rodent Control', ' Fumigation'], location: 'Pitampura, Delhi', bio: 'Professional pest management for residential and commercial properties.', rating: 4.5, total_reviews: 47, experience_years: 6, completion_rate: 96, availability: true, lat: 28.7012, lng: 77.1376, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-lime-500' },
  { id: 'w26', name: 'Kiran Bedi', email: 'kiran@example.com', phone: '+91 98765 43235', skills: ['Housekeeping', 'Elder Care', 'Cooking'], location: 'Janakpuri, Delhi', bio: 'Experienced housekeeper with elder care and home cooking expertise.', rating: 4.6, total_reviews: 52, experience_years: 5, completion_rate: 97, availability: true, lat: 28.6210, lng: 77.0856, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-teal-400' },
  { id: 'w27', name: 'Mohammad Ansari', email: 'ansari@example.com', phone: '+91 98765 43236', skills: ['Carpenter', 'Modular Kitchen', 'Wardrobe'], location: 'Faridabad Sector 15', bio: 'Specialized in modular kitchen and wardrobe design and installation.', rating: 4.7, total_reviews: 78, experience_years: 10, completion_rate: 95, availability: true, lat: 28.3761, lng: 77.3144, hourly_rate: 800, user_type: 'worker', avatar_color: 'bg-amber-500' },
  { id: 'w28', name: 'Lakshmi Devi', email: 'lakshmi@example.com', phone: '+91 98765 43237', skills: ['Home Cleaning', 'Carpet Cleaning', 'Sofa Cleaning'], location: 'Paschim Vihar, Delhi', bio: 'Deep cleaning specialist for homes, carpets, and upholstery.', rating: 4.8, total_reviews: 68, experience_years: 4, completion_rate: 98, availability: true, lat: 28.6679, lng: 77.0882, hourly_rate: 380, user_type: 'worker', avatar_color: 'bg-purple-400' },
  { id: 'w29', name: 'Harish Chandra', email: 'harish@example.com', phone: '+91 98765 43238', skills: ['Electrician', 'Smart Home', 'Security Systems'], location: 'Green Park, Delhi', bio: 'Smart home automation and security system installation expert.', rating: 4.6, total_reviews: 42, experience_years: 7, completion_rate: 94, availability: true, lat: 28.5606, lng: 77.2047, hourly_rate: 750, user_type: 'worker', avatar_color: 'bg-blue-500' },
  { id: 'w30', name: 'Sunil Kumar', email: 'sunil@example.com', phone: '+91 98765 43239', skills: ['Mason', 'Civil Work', 'Construction'], location: 'Alaknanda, Delhi', bio: 'Experienced mason for civil work, construction, and renovation projects.', rating: 4.3, total_reviews: 55, experience_years: 15, completion_rate: 90, availability: true, lat: 28.5359, lng: 77.2475, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-stone-500' },
  { id: 'w31', name: 'Rekha Sharma', email: 'rekha@example.com', phone: '+91 98765 43240', skills: ['Appliance Repair', 'Microwave', 'Geyser'], location: 'Vasant Kunj, Delhi', bio: 'Home appliance repair for microwaves, geysers, and kitchen appliances.', rating: 4.5, total_reviews: 61, experience_years: 6, completion_rate: 93, availability: true, lat: 28.5140, lng: 77.1579, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-orange-400' },
  { id: 'w32', name: 'Vikram Singh', email: 'vikrams@example.com', phone: '+91 98765 43241', skills: ['Driver Services', 'Corporate Transport', 'School Van'], location: 'Mehrauli, Delhi', bio: 'Professional driver for corporate transport and school van services.', rating: 4.4, total_reviews: 38, experience_years: 8, completion_rate: 92, availability: true, lat: 28.5243, lng: 77.1792, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-slate-500' },
  { id: 'w33', name: 'Amitabh Mishra', email: 'amitabh@example.com', phone: '+91 98765 43242', skills: ['RO Water Purifier Service', 'Water Filter', ' TDS'], location: 'Dilshad Garden, Delhi', bio: 'Water purifier specialist for all brands. TDS testing and filter replacement.', rating: 4.6, total_reviews: 35, experience_years: 4, completion_rate: 96, availability: true, lat: 28.6811, lng: 77.3159, hourly_rate: 420, user_type: 'worker', avatar_color: 'bg-cyan-400' },
  { id: 'w34', name: 'Nidhi Agarwal', email: 'nidhi@example.com', phone: '+91 98765 43243', skills: ['Security Guard', 'Event Security', 'Bouncer'], location: 'MG Road, Gurgaon', bio: 'Trained security personnel for events, parties, and corporate security.', rating: 4.5, total_reviews: 29, experience_years: 6, completion_rate: 98, availability: true, lat: 28.4755, lng: 77.0278, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-gray-500' },
  { id: 'w35', name: 'Pawan Kumar', email: 'pawan@example.com', phone: '+91 98765 43244', skills: ['Delivery Services', 'Furniture Moving', 'Heavy'], location: 'Naraina, Delhi', bio: 'Heavy item delivery and furniture moving within Delhi NCR.', rating: 4.2, total_reviews: 41, experience_years: 3, completion_rate: 95, availability: true, lat: 28.6139, lng: 77.1471, hourly_rate: 300, user_type: 'worker', avatar_color: 'bg-yellow-600' },
  { id: 'w36', name: 'Seema Yadav', email: 'seema@example.com', phone: '+91 98765 43245', skills: ['Painter', 'Waterproofing', 'Roof Repair'], location: 'Govindpuri, Delhi', bio: 'Painter and waterproofing specialist. Roof repair and texture finishing.', rating: 4.6, total_reviews: 58, experience_years: 8, completion_rate: 94, availability: true, lat: 28.5376, lng: 77.2679, hourly_rate: 580, user_type: 'worker', avatar_color: 'bg-violet-400' },
  { id: 'w37', name: 'Dinesh Patel', email: 'dinesh@example.com', phone: '+91 98765 43246', skills: ['Plumber', 'Sewage', 'Drainage'], location: 'Kirti Nagar, Delhi', bio: 'Expert in sewage cleaning, drainage repair, and pipe unclogging.', rating: 4.4, total_reviews: 76, experience_years: 9, completion_rate: 91, availability: true, lat: 28.6522, lng: 77.1316, hourly_rate: 520, user_type: 'worker', avatar_color: 'bg-blue-600' },
  { id: 'w38', name: 'Kamlesh Jain', email: 'kamlesh@example.com', phone: '+91 98765 43247', skills: ['Computer/Laptop Repair', 'Printer', 'Scanner'], location: ' Nehru Place, Delhi', bio: 'IT solutions including printer, scanner, and all computer peripherals.', rating: 4.5, total_reviews: 67, experience_years: 7, completion_rate: 93, availability: true, lat: 28.5496, lng: 77.2529, hourly_rate: 520, user_type: 'worker', avatar_color: 'bg-indigo-500' },
  { id: 'w39', name: 'Pushpa Rani', email: 'pushpa@example.com', phone: '+91 98765 43248', skills: ['Salon at Home', 'Mehendi', 'Mehndi'], location: 'Madipur, Delhi', bio: 'Traditional and bridal mehendi artist. Body art and temporary tattoos.', rating: 4.8, total_reviews: 48, experience_years: 10, completion_rate: 99, availability: true, lat: 28.6725, lng: 77.1137, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-amber-400' },
  { id: 'w40', name: 'Yogesh Kumar', email: 'yogesh@example.com', phone: '+91 98765 43249', skills: ['Washing Machine Repair', 'Dryer Repair'], location: 'Shalimar Bagh, Delhi', bio: 'Washing machine and clothes dryer repair specialist.', rating: 4.3, total_reviews: 44, experience_years: 5, completion_rate: 92, availability: true, lat: 28.7152, lng: 77.1528, hourly_rate: 420, user_type: 'worker', avatar_color: 'bg-sky-500' },
  { id: 'w41', name: 'Imran Siddiqui', email: 'imran@example.com', phone: '+91 98765 43250', skills: ['Electrician', 'Inverter Repair', 'UPS Installation'], location: 'Batla House, Delhi', bio: 'Expert electrician specializing in inverter and UPS systems for homes and offices.', rating: 4.7, total_reviews: 63, experience_years: 8, completion_rate: 96, availability: true, lat: 28.5653, lng: 77.2867, hourly_rate: 550, user_type: 'worker', avatar_color: 'bg-blue-600' },
  { id: 'w42', name: 'Shabana Begum', email: 'shabana@example.com', phone: '+91 98765 43251', skills: ['Salon at Home', 'Threading', 'Facial'], location: 'Zakir Nagar, Delhi', bio: 'Professional beautician offering threading, facials, and skin care treatments at home.', rating: 4.8, total_reviews: 55, experience_years: 7, completion_rate: 98, availability: true, lat: 28.5630, lng: 77.2820, hourly_rate: 500, user_type: 'worker', avatar_color: 'bg-rose-500' },
  { id: 'w43', name: 'Naveen Jha', email: 'naveen@example.com', phone: '+91 98765 43252', skills: ['Plumber', 'Water Tank Cleaning', 'Motor Repair'], location: 'Okhla Phase 1, Delhi', bio: 'Plumbing expert with specialization in overhead tank cleaning and motor pump repairs.', rating: 4.5, total_reviews: 71, experience_years: 9, completion_rate: 94, availability: true, lat: 28.5330, lng: 77.2710, hourly_rate: 480, user_type: 'worker', avatar_color: 'bg-cyan-600' },
  { id: 'w44', name: 'Aarti Chauhan', email: 'aarti@example.com', phone: '+91 98765 43253', skills: ['Home Cleaning', 'Office Cleaning', 'Post-Construction Cleaning'], location: 'New Friends Colony, Delhi', bio: 'Deep cleaning specialist for post-construction, move-in, and office spaces.', rating: 4.6, total_reviews: 48, experience_years: 4, completion_rate: 97, availability: true, lat: 28.5640, lng: 77.2570, hourly_rate: 380, user_type: 'worker', avatar_color: 'bg-emerald-500' },
  { id: 'w45', name: 'Mohd Tariq', email: 'tariq@example.com', phone: '+91 98765 43254', skills: ['Carpenter', 'Door Repair', 'Window Fitting'], location: 'Sukhdev Vihar, Delhi', bio: 'Skilled carpenter for door installation, window fitting, and wooden frame repairs.', rating: 4.4, total_reviews: 59, experience_years: 11, completion_rate: 93, availability: true, lat: 28.5560, lng: 77.2690, hourly_rate: 600, user_type: 'worker', avatar_color: 'bg-amber-600' },
  { id: 'w46', name: 'Geeta Rani', email: 'geeta@example.com', phone: '+91 98765 43255', skills: ['Housekeeping', 'Baby Sitting', 'Cooking'], location: 'Okhla Phase 2, Delhi', bio: 'Trained housekeeper offering babysitting, cooking, and household management services.', rating: 4.7, total_reviews: 41, experience_years: 6, completion_rate: 98, availability: true, lat: 28.5300, lng: 77.2750, hourly_rate: 350, user_type: 'worker', avatar_color: 'bg-pink-400' },
  { id: 'w47', name: 'Rajendra Prasad', email: 'rajendra@example.com', phone: '+91 98765 43256', skills: ['AC Repair', 'Cooler Servicing', 'Heating Systems'], location: 'Gurgaon Sector 56', bio: 'HVAC technician for AC, desert cooler, and central heating system maintenance.', rating: 4.6, total_reviews: 82, experience_years: 10, completion_rate: 95, availability: true, lat: 28.4220, lng: 77.0400, hourly_rate: 650, user_type: 'worker', avatar_color: 'bg-sky-600' },
  { id: 'w48', name: 'Sakina Khatun', email: 'sakina@example.com', phone: '+91 98765 43257', skills: ['Tailor Services', 'Embroidery', 'Kurti Stitching'], location: 'Batla House, Delhi', bio: 'Expert tailor for ladies garments, embroidery, and traditional ethnic wear stitching.', rating: 4.8, total_reviews: 53, experience_years: 12, completion_rate: 99, availability: true, lat: 28.5660, lng: 77.2880, hourly_rate: 400, user_type: 'worker', avatar_color: 'bg-fuchsia-400' },
  { id: 'w49', name: 'Anil Rawat', email: 'anil@example.com', phone: '+91 98765 43258', skills: ['Painter', 'POP Work', 'False Ceiling'], location: 'Noida Sector 18', bio: 'Professional painter with expertise in POP design, false ceiling, and gypsum work.', rating: 4.5, total_reviews: 66, experience_years: 8, completion_rate: 94, availability: true, lat: 28.5692, lng: 77.3217, hourly_rate: 620, user_type: 'worker', avatar_color: 'bg-violet-600' },
  { id: 'w50', name: 'Mumtaz Ali', email: 'mumtaz@example.com', phone: '+91 98765 43259', skills: ['Mobile Repair', 'Chip Level Repair', 'Data Recovery'], location: 'Zakir Nagar, Delhi', bio: 'Advanced mobile repair including chip-level servicing and data recovery for all brands.', rating: 4.6, total_reviews: 87, experience_years: 6, completion_rate: 93, availability: true, lat: 28.5625, lng: 77.2835, hourly_rate: 450, user_type: 'worker', avatar_color: 'bg-indigo-600' },
  { id: 'w51', name: 'Sunanda Devi', email: 'sunanda@example.com', phone: '+91 98765 43260', skills: ['Pest Control', 'Bed Bug Treatment', 'Cockroach Control'], location: 'New Friends Colony, Delhi', bio: 'Certified pest control professional with safe chemical-free options for families.', rating: 4.7, total_reviews: 39, experience_years: 5, completion_rate: 97, availability: true, lat: 28.5650, lng: 77.2580, hourly_rate: 480, user_type: 'worker', avatar_color: 'bg-lime-600' },
  { id: 'w52', name: 'Farhan Ahmed', email: 'farhan@example.com', phone: '+91 98765 43261', skills: ['Computer/Laptop Repair', 'CCTV Installation', 'Networking'], location: 'Sukhdev Vihar, Delhi', bio: 'IT solutions expert for CCTV setup, networking, and computer hardware repair.', rating: 4.5, total_reviews: 57, experience_years: 7, completion_rate: 95, availability: true, lat: 28.5550, lng: 77.2700, hourly_rate: 580, user_type: 'worker', avatar_color: 'bg-gray-600' },
  { id: 'w53', name: 'Kamla Bai', email: 'kamla@example.com', phone: '+91 98765 43262', skills: ['Housekeeping', 'Ironing', 'Laundry'], location: 'Gurgaon Sector 14', bio: 'Experienced housekeeper providing ironing, laundry, and daily household cleaning.', rating: 4.3, total_reviews: 46, experience_years: 8, completion_rate: 91, availability: true, lat: 28.4680, lng: 77.0260, hourly_rate: 280, user_type: 'worker', avatar_color: 'bg-teal-500' },
  { id: 'w54', name: 'Bharat Singh', email: 'bharat@example.com', phone: '+91 98765 43263', skills: ['Mason', 'Marble Polishing', 'Tile Cutting'], location: 'Noida Sector 44', bio: 'Master mason for marble flooring, tile cutting, and precision stone work installations.', rating: 4.6, total_reviews: 74, experience_years: 14, completion_rate: 96, availability: true, lat: 28.5780, lng: 77.3450, hourly_rate: 700, user_type: 'worker', avatar_color: 'bg-stone-600' },
  { id: 'w55', name: 'Zoya Khan', email: 'zoya@example.com', phone: '+91 98765 43264', skills: ['Salon at Home', 'Makeup Artist', 'Hair Spa'], location: 'Okhla, Delhi', bio: 'Professional makeup artist and hair spa specialist. Bridal, party, and casual looks.', rating: 4.9, total_reviews: 92, experience_years: 8, completion_rate: 99, availability: true, lat: 28.5310, lng: 77.2720, hourly_rate: 900, user_type: 'worker', avatar_color: 'bg-rose-400' },
]

export const dummyServices = [
  { id: 's1', title: 'Professional Home Cleaning', description: 'Complete home cleaning with eco-friendly products. Includes kitchen, bathroom, and all living areas. Deep cleaning available.', category: 'Home Cleaning', price: 1500, location: 'Connaught Place, Delhi', worker_id: 'w2', worker_name: 'Priya Singh', rating: 4.9, total_reviews: 89, is_active: true, createdAt: '2025-12-01T10:00:00Z', updatedAt: '2026-01-15T10:00:00Z' },
  { id: 's2', title: 'Plumbing & Pipe Repair', description: 'Expert plumbing services - leak repair, pipe installation, bathroom fitting, and drainage solutions. Emergency service available.', category: 'Plumber', price: 800, location: 'Lajpat Nagar, Delhi', worker_id: 'w1', worker_name: 'Rajesh Kumar', rating: 4.8, total_reviews: 124, is_active: true, createdAt: '2025-11-20T10:00:00Z', updatedAt: '2026-01-10T10:00:00Z' },
  { id: 's3', title: 'Electrical Wiring & Repair', description: 'Complete electrical solutions - wiring, switchboard installation, fan/light fitting, MCB and safety inspection.', category: 'Electrician', price: 1200, location: 'Karol Bagh, Delhi', worker_id: 'w3', worker_name: 'Amar Patel', rating: 4.7, total_reviews: 156, is_active: true, createdAt: '2025-11-15T10:00:00Z', updatedAt: '2026-01-05T10:00:00Z' },
  { id: 's4', title: 'Interior & Exterior Painting', description: 'Transform your space with professional painting. Texture painting, wall art, and expert color consultation included.', category: 'Painter', price: 2500, location: 'Rajouri Garden, Delhi', worker_id: 'w4', worker_name: 'Sunita Devi', rating: 4.6, total_reviews: 67, is_active: true, createdAt: '2025-12-10T10:00:00Z', updatedAt: '2026-01-20T10:00:00Z' },
  { id: 's5', title: 'Custom Furniture & Carpentry', description: 'Bespoke woodwork - custom furniture, cabinet installation, door repair, and wood polishing by skilled carpenters.', category: 'Carpenter', price: 3000, location: 'Dwarka, Delhi', worker_id: 'w5', worker_name: 'Vikram Choudhary', rating: 4.5, total_reviews: 98, is_active: true, createdAt: '2025-11-25T10:00:00Z', updatedAt: '2026-01-12T10:00:00Z' },
  { id: 's6', title: 'Housekeeping & Gardening', description: 'Professional housekeeping - lawn maintenance, indoor plant care, daily cleaning, and terrace garden setup.', category: 'Housekeeping', price: 1000, location: 'Hauz Khas, Delhi', worker_id: 'w6', worker_name: 'Meena Kumari', rating: 4.8, total_reviews: 45, is_active: true, createdAt: '2025-12-05T10:00:00Z', updatedAt: '2026-01-18T10:00:00Z' },
  { id: 's7', title: 'AC Installation & Repair', description: 'Split AC, window AC installation, gas refilling, compressor repair, and annual maintenance. All brands covered.', category: 'AC Repair', price: 1800, location: 'Saket, Delhi', worker_id: 'w7', worker_name: 'Arjun Reddy', rating: 4.7, total_reviews: 112, is_active: true, createdAt: '2025-12-08T10:00:00Z', updatedAt: '2026-01-22T10:00:00Z' },
  { id: 's8', title: 'Salon & Beauty at Home', description: 'Complete salon experience at your doorstep - haircut, facial, waxing, bridal makeup, and grooming packages.', category: 'Salon at Home', price: 1500, location: 'Khan Market, Delhi', worker_id: 'w8', worker_name: 'Fatima Khan', rating: 4.9, total_reviews: 78, is_active: true, createdAt: '2025-12-12T10:00:00Z', updatedAt: '2026-01-25T10:00:00Z' },
  { id: 's9', title: 'Masonry & Tile Work', description: 'Professional masonry - wall construction, tile fitting, plastering, waterproofing, and bathroom renovation.', category: 'Mason', price: 2000, location: 'Rohini, Delhi', worker_id: 'w9', worker_name: 'Suresh Yadav', rating: 4.4, total_reviews: 86, is_active: true, createdAt: '2025-12-15T10:00:00Z', updatedAt: '2026-01-28T10:00:00Z' },
  { id: 's10', title: 'Pest Control Treatment', description: 'Complete pest control - cockroach, termite, bed bug, mosquito, and rodent treatment. Safe for kids and pets.', category: 'Pest Control', price: 2500, location: 'Defence Colony, Delhi', worker_id: 'w10', worker_name: 'Kavitha Nair', rating: 4.6, total_reviews: 54, is_active: true, createdAt: '2025-12-18T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: 's11', title: 'Mobile Phone Repair', description: 'Screen replacement, battery change, charging port fix, software issues, and water damage repair. All brands.', category: 'Mobile Repair', price: 500, location: 'Chandni Chowk, Delhi', worker_id: 'w11', worker_name: 'Rohit Sharma', rating: 4.5, total_reviews: 132, is_active: true, createdAt: '2025-12-20T10:00:00Z', updatedAt: '2026-02-03T10:00:00Z' },
  { id: 's12', title: 'Laptop & Computer Repair', description: 'Laptop repair, OS installation, virus removal, data recovery, RAM/SSD upgrade, and networking setup.', category: 'Computer/Laptop Repair', price: 800, location: 'Noida Sector 62', worker_id: 'w12', worker_name: 'Deepak Mishra', rating: 4.7, total_reviews: 91, is_active: true, createdAt: '2025-12-22T10:00:00Z', updatedAt: '2026-02-05T10:00:00Z' },
  { id: 's13', title: 'Washing Machine Repair', description: 'Repair for all types - front load, top load, semi-automatic. Drum, motor, PCB, and drain pump servicing.', category: 'Washing Machine Repair', price: 700, location: 'Noida Sector 15', worker_id: 'w15', worker_name: 'Manoj Tiwari', rating: 4.4, total_reviews: 58, is_active: true, createdAt: '2025-12-25T10:00:00Z', updatedAt: '2026-02-08T10:00:00Z' },
  { id: 's14', title: 'RO Purifier Service', description: 'RO water purifier installation, filter change, membrane replacement, and annual maintenance contract.', category: 'RO Water Purifier Service', price: 600, location: 'Barakhamba Road, Delhi', worker_id: 'w16', worker_name: 'Sanjay Verma', rating: 4.5, total_reviews: 42, is_active: true, createdAt: '2025-12-28T10:00:00Z', updatedAt: '2026-02-10T10:00:00Z' },
  { id: 's15', title: 'Refrigerator Repair', description: 'Fridge not cooling? Gas refill, compressor, thermostat, and door gasket repair. Single and double door models.', category: 'Refrigerator Repair', price: 900, location: 'Saket, Delhi', worker_id: 'w7', worker_name: 'Arjun Reddy', rating: 4.6, total_reviews: 73, is_active: true, createdAt: '2026-01-02T10:00:00Z', updatedAt: '2026-02-12T10:00:00Z' },
  { id: 's16', title: 'Driver on Demand', description: 'Professional driver for city rides, airport transfers, outstation trips, and weddings. Commercial license holder.', category: 'Driver Services', price: 1200, location: 'Rajiv Chowk, Delhi', worker_id: 'w13', worker_name: 'Ramesh Gupta', rating: 4.3, total_reviews: 64, is_active: true, createdAt: '2026-01-05T10:00:00Z', updatedAt: '2026-02-15T10:00:00Z' },
  { id: 's17', title: 'Tailoring & Alterations', description: 'Expert stitching - blouse, kurta, suits, alterations, hemming, and custom outfits. Pickup & delivery available.', category: 'Tailor Services', price: 400, location: 'Chittaranjan Park, Delhi', worker_id: 'w14', worker_name: 'Anita Joshi', rating: 4.8, total_reviews: 76, is_active: true, createdAt: '2026-01-08T10:00:00Z', updatedAt: '2026-02-18T10:00:00Z' },
  { id: 's18', title: 'Security Guard Service', description: 'Trained security personnel for events, offices, and residential complexes. Day and night shifts available.', category: 'Security Guard', price: 800, location: 'Gurgaon Cyber City', worker_id: 'w17', worker_name: 'Prakash Raj', rating: 4.6, total_reviews: 38, is_active: true, createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-02-20T10:00:00Z' },
  { id: 's19', title: 'Same-Day Delivery', description: 'Reliable same-day pickup and delivery within Delhi NCR. Documents, parcels, and fragile items handled with care.', category: 'Delivery Services', price: 200, location: 'Golf Course Road, Gurgaon', worker_id: 'w18', worker_name: 'Pooja Bansal', rating: 4.3, total_reviews: 49, is_active: true, createdAt: '2026-01-12T10:00:00Z', updatedAt: '2026-02-22T10:00:00Z' },
  { id: 's20', title: 'Appliance Installation', description: 'Installation of TV, geyser, chimney, microwave wall mount, and ceiling fan. Includes wiring and testing.', category: 'Appliance Repair', price: 600, location: 'Karol Bagh, Delhi', worker_id: 'w3', worker_name: 'Amar Patel', rating: 4.5, total_reviews: 63, is_active: true, createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-02-25T10:00:00Z' },
  { id: 's21', title: 'Smart Home Setup', description: 'Complete smart home automation - lights, security cameras, door locks, and voice assistants installation.', category: 'Electrician', price: 3500, location: 'Green Park, Delhi', worker_id: 'w29', worker_name: 'Harish Chandra', rating: 4.6, total_reviews: 42, is_active: true, createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-28T10:00:00Z' },
  { id: 's22', title: 'Modular Kitchen Installation', description: 'Custom modular kitchen design and installation. Premium finishes and modern layouts.', category: 'Carpenter', price: 25000, location: 'Faridabad Sector 15', worker_id: 'w27', worker_name: 'Mohammad Ansari', rating: 4.7, total_reviews: 78, is_active: true, createdAt: '2026-02-05T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: 's23', title: 'Carpet & Sofa Cleaning', description: 'Professional deep cleaning for carpets, sofas, and mattresses. Stain removal and sanitization included.', category: 'Home Cleaning', price: 1200, location: 'Paschim Vihar, Delhi', worker_id: 'w28', worker_name: 'Lakshmi Devi', rating: 4.8, total_reviews: 68, is_active: true, createdAt: '2026-02-10T10:00:00Z', updatedAt: '2026-03-05T10:00:00Z' },
  { id: 's24', title: 'Bridal Makeup Package', description: 'Complete bridal makeup with hairstyling, draping, and mehendi coordination. Premium products used.', category: 'Salon at Home', price: 5000, location: 'Greater Kailash, Delhi', worker_id: 'w22', worker_name: 'Preeti Gupta', rating: 4.9, total_reviews: 112, is_active: true, createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-03-10T10:00:00Z' },
  { id: 's25', title: 'Generator Repair & Service', description: 'Expert generator servicing, repair, and annual maintenance. Both petrol and diesel generators.', category: 'Electrician', price: 2000, location: 'Paharganj, Delhi', worker_id: 'w19', worker_name: 'Vijay Malhotra', rating: 4.6, total_reviews: 72, is_active: true, createdAt: '2026-02-20T10:00:00Z', updatedAt: '2026-03-15T10:00:00Z' },
]

export const dummyJobs = [
  { id: 'j1', title: 'Senior React Developer', company: 'TechVista Solutions', location: 'Connaught Place, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 1200000, salary_max: 1800000, description: 'Build modern web applications using React, Node.js, and cloud technologies. 3+ years experience required.', skills_required: ['React', 'Node.js', 'TypeScript', 'AWS'], is_active: true, employer_id: 'e1', posted_by: 'TechVista HR', createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-01-10T10:00:00Z' },
  { id: 'j2', title: 'UI/UX Designer', company: 'DesignCraft Studio', location: 'Hauz Khas, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 800000, salary_max: 1400000, description: 'Design user-centered interfaces for web and mobile products. Figma and prototyping skills required.', skills_required: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'], is_active: true, employer_id: 'e2', posted_by: 'DesignCraft HR', createdAt: '2026-01-08T10:00:00Z', updatedAt: '2026-01-08T10:00:00Z' },
  { id: 'j3', title: 'Python Backend Developer', company: 'DataFlow Inc.', location: 'Noida Sector 62', type: 'Full-time', employment_type: 'full_time', salary_min: 1000000, salary_max: 1600000, description: 'Develop APIs and microservices using Python, FastAPI, and PostgreSQL. DevOps experience a plus.', skills_required: ['Python', 'FastAPI', 'PostgreSQL', 'Docker'], is_active: true, employer_id: 'e3', posted_by: 'DataFlow HR', createdAt: '2026-01-05T10:00:00Z', updatedAt: '2026-01-05T10:00:00Z' },
  { id: 'j4', title: 'Digital Marketing Manager', company: 'GrowthPulse Media', location: 'Khan Market, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 900000, salary_max: 1500000, description: 'Lead digital marketing strategies and campaigns for growing D2C brands across Delhi NCR.', skills_required: ['SEO', 'SEM', 'Social Media', 'Analytics'], is_active: true, employer_id: 'e4', posted_by: 'GrowthPulse HR', createdAt: '2026-01-03T10:00:00Z', updatedAt: '2026-01-03T10:00:00Z' },
  { id: 'j5', title: 'DevOps Engineer', company: 'CloudNine Systems', location: 'Gurgaon Cyber City', type: 'Full-time', employment_type: 'full_time', salary_min: 1400000, salary_max: 2200000, description: 'Manage CI/CD pipelines, Kubernetes clusters, and cloud infrastructure on AWS/GCP.', skills_required: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD'], is_active: true, employer_id: 'e5', posted_by: 'CloudNine HR', createdAt: '2026-01-12T10:00:00Z', updatedAt: '2026-01-12T10:00:00Z' },
  { id: 'j6', title: 'Data Analyst', company: 'InsightEdge Analytics', location: 'Noida Sector 15', type: 'Full-time', employment_type: 'full_time', salary_min: 600000, salary_max: 1000000, description: 'Analyze large datasets, create dashboards, and generate actionable business insights.', skills_required: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics'], is_active: true, employer_id: 'e6', posted_by: 'InsightEdge HR', createdAt: '2026-01-14T10:00:00Z', updatedAt: '2026-01-14T10:00:00Z' },
  { id: 'j7', title: 'Content Writer', company: 'WordSmith Media', location: 'Defence Colony, Delhi', type: 'Part-time', employment_type: 'part_time', salary_min: 300000, salary_max: 600000, description: 'Write engaging blog posts, website copy, and social media content for tech and lifestyle brands.', skills_required: ['Content Writing', 'SEO Writing', 'Copywriting', 'Research'], is_active: true, employer_id: 'e7', posted_by: 'WordSmith HR', createdAt: '2026-01-16T10:00:00Z', updatedAt: '2026-01-16T10:00:00Z' },
  { id: 'j8', title: 'Product Manager', company: 'FinServe Technologies', location: 'Golf Course Road, Gurgaon', type: 'Full-time', employment_type: 'full_time', salary_min: 1800000, salary_max: 2800000, description: 'Own the product roadmap for our fintech SaaS platform. Drive strategy, prioritization, and GTM.', skills_required: ['Product Strategy', 'Agile', 'Data Analysis', 'UX Principles'], is_active: true, employer_id: 'e8', posted_by: 'FinServe HR', createdAt: '2026-01-18T10:00:00Z', updatedAt: '2026-01-18T10:00:00Z' },
  { id: 'j9', title: 'Mobile App Developer', company: 'AppNest Solutions', location: 'Saket, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 1100000, salary_max: 1700000, description: 'Develop cross-platform mobile applications using React Native or Flutter.', skills_required: ['React Native', 'Flutter', 'iOS', 'Android', 'JavaScript'], is_active: true, employer_id: 'e9', posted_by: 'AppNest HR', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-01-20T10:00:00Z' },
  { id: 'j10', title: 'Sales Executive', company: 'RetailMax Corp', location: 'Rajouri Garden, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 400000, salary_max: 800000, description: 'Drive B2B sales for our retail solutions. Field work and client meetings required.', skills_required: ['Sales', 'B2B', 'Communication', 'Negotiation'], is_active: true, employer_id: 'e10', posted_by: 'RetailMax HR', createdAt: '2026-01-22T10:00:00Z', updatedAt: '2026-01-22T10:00:00Z' },
  { id: 'j11', title: 'Graphic Designer', company: 'CreativeHub Agency', location: 'Dwarka, Delhi', type: 'Freelance', employment_type: 'freelance', salary_min: 250000, salary_max: 500000, description: 'Create stunning visuals for social media, websites, and print media.', skills_required: ['Photoshop', 'Illustrator', 'Canva', 'Social Media Design'], is_active: true, employer_id: 'e11', posted_by: 'CreativeHub HR', createdAt: '2026-01-24T10:00:00Z', updatedAt: '2026-01-24T10:00:00Z' },
  { id: 'j12', title: 'HR Manager', company: 'PeopleFirst HR', location: 'Connaught Place, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 700000, salary_max: 1200000, description: 'Manage end-to-end HR operations including recruitment, onboarding, and employee relations.', skills_required: ['HR', 'Recruitment', 'Payroll', 'Employee Relations'], is_active: true, employer_id: 'e12', posted_by: 'PeopleFirst HR', createdAt: '2026-01-26T10:00:00Z', updatedAt: '2026-01-26T10:00:00Z' },
  { id: 'j13', title: 'Video Editor', company: 'StreamVision', location: 'Rohini, Delhi', type: 'Contract', employment_type: 'contract', salary_min: 350000, salary_max: 700000, description: 'Edit promotional videos, YouTube content, and social media reels.', skills_required: ['Premiere Pro', 'Final Cut', 'DaVinci Resolve', 'After Effects'], is_active: true, employer_id: 'e13', posted_by: 'StreamVision HR', createdAt: '2026-01-28T10:00:00Z', updatedAt: '2026-01-28T10:00:00Z' },
  { id: 'j14', title: 'Accountant', company: 'FinTrack Solutions', location: 'Karol Bagh, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 450000, salary_max: 900000, description: 'Handle day-to-day accounting, GST filing, and financial reporting.', skills_required: ['Tally', 'Excel', 'GST', 'Taxation', 'Accounting'], is_active: true, employer_id: 'e14', posted_by: 'FinTrack HR', createdAt: '2026-01-30T10:00:00Z', updatedAt: '2026-01-30T10:00:00Z' },
  { id: 'j15', title: 'Customer Support Executive', company: 'HelpDesk Plus', location: 'Lajpat Nagar, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 250000, salary_max: 450000, description: 'Handle customer queries via phone, email, and chat. Technical background preferred.', skills_required: ['Communication', 'Problem Solving', 'CRM', 'Technical Support'], is_active: true, employer_id: 'e15', posted_by: 'HelpDesk HR', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: 'j16', title: 'Machine Learning Engineer', company: 'AI Innovators', location: 'Noida Sector 62', type: 'Full-time', employment_type: 'full_time', salary_min: 1500000, salary_max: 2500000, description: 'Build and deploy machine learning models for production use cases.', skills_required: ['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'Statistics'], is_active: true, employer_id: 'e16', posted_by: 'AI Innovators HR', createdAt: '2026-02-03T10:00:00Z', updatedAt: '2026-02-03T10:00:00Z' },
  { id: 'j17', title: 'Social Media Manager', company: 'BrandBoost', location: 'Greater Kailash, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 400000, salary_max: 800000, description: 'Manage social media presence, create content calendars, and grow engagement.', skills_required: ['Social Media', 'Content Creation', 'Analytics', 'Community Management'], is_active: true, employer_id: 'e17', posted_by: 'BrandBoost HR', createdAt: '2026-02-05T10:00:00Z', updatedAt: '2026-02-05T10:00:00Z' },
  { id: 'j18', title: 'Quality Assurance Engineer', company: 'TestMaster QA', location: 'Gurgaon Sector 14', type: 'Full-time', employment_type: 'full_time', salary_min: 600000, salary_max: 1100000, description: 'Manual and automated testing of web and mobile applications.', skills_required: ['Selenium', 'JIRA', 'API Testing', 'Automation', 'Test Cases'], is_active: true, employer_id: 'e18', posted_by: 'TestMaster HR', createdAt: '2026-02-07T10:00:00Z', updatedAt: '2026-02-07T10:00:00Z' },
  { id: 'j19', title: 'Business Development Manager', company: 'ExpandX', location: 'Nehru Place, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 800000, salary_max: 1500000, description: 'Identify business opportunities, build partnerships, and drive revenue growth.', skills_required: ['Business Development', 'Sales', 'Negotiation', 'Market Research'], is_active: true, employer_id: 'e19', posted_by: 'ExpandX HR', createdAt: '2026-02-09T10:00:00Z', updatedAt: '2026-02-09T10:00:00Z' },
  { id: 'j20', title: 'Network Administrator', company: 'NetSecure IT', location: 'Janakpuri, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 500000, salary_max: 900000, description: 'Manage enterprise network infrastructure, firewalls, and security systems.', skills_required: ['Networking', 'Cisco', 'Firewall', 'Security', 'Linux'], is_active: true, employer_id: 'e20', posted_by: 'NetSecure HR', createdAt: '2026-02-11T10:00:00Z', updatedAt: '2026-02-11T10:00:00Z' },
  { id: 'j21', title: 'React Native Developer', company: 'MobileFirst Apps', location: 'Saket Mall, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 1000000, salary_max: 1600000, description: 'Build and maintain cross-platform mobile applications using React Native.', skills_required: ['React Native', 'JavaScript', 'TypeScript', 'Redux', 'REST APIs'], is_active: true, employer_id: 'e21', posted_by: 'MobileFirst HR', createdAt: '2026-02-13T10:00:00Z', updatedAt: '2026-02-13T10:00:00Z' },
  { id: 'j22', title: 'Legal Advisor', company: 'JurisPrime Law', location: 'Connaught Place, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 900000, salary_max: 1800000, description: 'Provide legal advice on corporate matters, contracts, and regulatory compliance.', skills_required: ['Corporate Law', 'Contracts', 'Compliance', 'Legal Drafting'], is_active: true, employer_id: 'e22', posted_by: 'JurisPrime HR', createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-02-15T10:00:00Z' },
  { id: 'j23', title: 'Warehouse Manager', company: 'SwiftLogistics', location: 'Narela, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 450000, salary_max: 850000, description: 'Oversee warehouse operations, inventory management, and team coordination.', skills_required: ['Warehouse Management', 'Inventory', 'Logistics', 'Team Management'], is_active: true, employer_id: 'e23', posted_by: 'SwiftLog HR', createdAt: '2026-02-17T10:00:00Z', updatedAt: '2026-02-17T10:00:00Z' },
  { id: 'j24', title: 'Interior Designer', company: 'SpaceDesign Studio', location: 'Vasant Kunj, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 550000, salary_max: 1100000, description: 'Design residential and commercial interiors with AutoCAD and 3D visualization.', skills_required: ['AutoCAD', '3D Max', 'Interior Design', 'Space Planning', 'Materials'], is_active: true, employer_id: 'e24', posted_by: 'SpaceDesign HR', createdAt: '2026-02-19T10:00:00Z', updatedAt: '2026-02-19T10:00:00Z' },
  { id: 'j25', title: 'Tele Caller', company: 'LeadGen Pro', location: 'Pitampura, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 200000, salary_max: 400000, description: 'Make outbound calls to generate leads and schedule appointments.', skills_required: ['Communication', 'Cold Calling', 'CRM', 'Microsoft Excel'], is_active: true, employer_id: 'e25', posted_by: 'LeadGen HR', createdAt: '2026-02-21T10:00:00Z', updatedAt: '2026-02-21T10:00:00Z' },
  { id: 'j26', title: 'Cyber Security Analyst', company: 'SecureNet Solutions', location: 'Gurgaon Cyber Hub', type: 'Full-time', employment_type: 'full_time', salary_min: 1000000, salary_max: 2000000, description: 'Monitor security systems, conduct vulnerability assessments, and respond to incidents.', skills_required: ['Security', 'Penetration Testing', 'SIEM', 'Network Security', 'Python'], is_active: true, employer_id: 'e26', posted_by: 'SecureNet HR', createdAt: '2026-02-23T10:00:00Z', updatedAt: '2026-02-23T10:00:00Z' },
  { id: 'j27', title: 'Content Strategist', company: 'MediaMinds', location: 'Hauz Khas Village, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 600000, salary_max: 1200000, description: 'Develop content strategies, manage editorial calendars, and optimize for SEO.', skills_required: ['Content Strategy', 'SEO', 'Analytics', 'Copywriting', 'Marketing'], is_active: true, employer_id: 'e27', posted_by: 'MediaMinds HR', createdAt: '2026-02-25T10:00:00Z', updatedAt: '2026-02-25T10:00:00Z' },
  { id: 'j28', title: 'Tally Operator', company: 'AccountsHub', location: 'Karol Bagh, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 220000, salary_max: 400000, description: 'Maintain accounting records using Tally ERP. GST and TDS filing.', skills_required: ['Tally', 'Accounting', 'GST', 'TDS', 'Excel'], is_active: true, employer_id: 'e28', posted_by: 'AccountsHub HR', createdAt: '2026-02-27T10:00:00Z', updatedAt: '2026-02-27T10:00:00Z' },
  { id: 'j29', title: 'PHP Developer', company: 'WebCraft India', location: 'Dwarka Sector 12, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 500000, salary_max: 900000, description: 'Develop and maintain PHP-based web applications and WordPress sites.', skills_required: ['PHP', 'WordPress', 'MySQL', 'Laravel', 'JavaScript'], is_active: true, employer_id: 'e29', posted_by: 'WebCraft HR', createdAt: '2026-03-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: 'j30', title: 'Fitness Trainer', company: 'FitLife Gym', location: 'Rajouri Garden, Delhi', type: 'Full-time', employment_type: 'full_time', salary_min: 300000, salary_max: 600000, description: 'Train clients, design workout plans, and conduct group fitness sessions.', skills_required: ['Fitness Training', 'Nutrition', 'Yoga', 'Personal Training', 'Group Sessions'], is_active: true, employer_id: 'e30', posted_by: 'FitLife HR', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' },
]

export const dummyGigs = [
  { id: 'g1', title: 'Build a Landing Page', description: 'Need a responsive landing page built with React and Tailwind CSS. Must be mobile-first.', budget: 15000, category: 'Web Development', skills: ['React', 'Tailwind CSS', 'Responsive Design'], status: 'open', employer_id: 'e1', location: 'Connaught Place, Delhi', createdAt: '2026-01-12T10:00:00Z', updatedAt: '2026-01-12T10:00:00Z' },
  { id: 'g2', title: 'Logo Design for Startup', description: 'Design a modern, minimal logo for a tech startup. Deliverables: PNG, SVG, and brand guidelines.', budget: 5000, category: 'Graphic Design', skills: ['Logo Design', 'Branding', 'Illustrator'], status: 'open', employer_id: 'e2', location: 'Hauz Khas, Delhi', createdAt: '2026-01-11T10:00:00Z', updatedAt: '2026-01-11T10:00:00Z' },
  { id: 'g3', title: 'Social Media Content (30 Days)', description: 'Create 30 days of social media content for Instagram and LinkedIn. Graphics + captions.', budget: 20000, category: 'Digital Marketing', skills: ['Content Writing', 'Social Media', 'Canva'], status: 'open', employer_id: 'e3', location: 'Khan Market, Delhi', createdAt: '2026-01-09T10:00:00Z', updatedAt: '2026-01-09T10:00:00Z' },
  { id: 'g4', title: 'Mobile App Testing', description: 'QA testing for an Android/iOS app. Write test cases, find bugs, and report with screenshots.', budget: 8000, category: 'QA Testing', skills: ['Manual Testing', 'Bug Reporting', 'Mobile'], status: 'open', employer_id: 'e4', location: 'Noida Sector 62', createdAt: '2026-01-07T10:00:00Z', updatedAt: '2026-01-07T10:00:00Z' },
  { id: 'g5', title: 'Product Photography (50 items)', description: 'Professional product photography for an e-commerce store. White background, lifestyle shots.', budget: 12000, category: 'Photography', skills: ['Product Photography', 'Photo Editing', 'Lightroom'], status: 'open', employer_id: 'e5', location: 'Rajouri Garden, Delhi', createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-01-15T10:00:00Z' },
  { id: 'g6', title: 'WordPress E-commerce Site', description: 'Set up a WooCommerce store with payment gateway, 50 products, and responsive theme.', budget: 25000, category: 'Web Development', skills: ['WordPress', 'WooCommerce', 'PHP'], status: 'open', employer_id: 'e6', location: 'Dwarka, Delhi', createdAt: '2026-01-17T10:00:00Z', updatedAt: '2026-01-17T10:00:00Z' },
  { id: 'g7', title: 'SEO Audit & Optimization', description: 'Complete SEO audit for a SaaS website. On-page optimization, keyword research, and backlink strategy.', budget: 10000, category: 'Digital Marketing', skills: ['SEO', 'Google Analytics', 'Ahrefs'], status: 'open', employer_id: 'e7', location: 'Gurgaon Cyber City', createdAt: '2026-01-19T10:00:00Z', updatedAt: '2026-01-19T10:00:00Z' },
  { id: 'g8', title: 'Data Entry (1000 Records)', description: 'Enter product data from PDF catalogs into Excel/Google Sheets. Must be accurate and formatted.', budget: 3000, category: 'Data Entry', skills: ['Data Entry', 'Excel', 'Google Sheets'], status: 'open', employer_id: 'e8', location: 'Chandni Chowk, Delhi', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-01-20T10:00:00Z' },
  { id: 'g9', title: 'Flutter App Development', description: 'Develop a cross-platform mobile app for food delivery. Include cart, payments, and order tracking.', budget: 50000, category: 'Mobile Development', skills: ['Flutter', 'Dart', 'Firebase', 'Payment Gateway'], status: 'open', employer_id: 'e9', location: 'Saket, Delhi', createdAt: '2026-01-22T10:00:00Z', updatedAt: '2026-01-22T10:00:00Z' },
  { id: 'g10', title: 'Corporate Video (3 minutes)', description: 'Create a professional corporate video for our company intro. Include animation and voiceover.', budget: 18000, category: 'Video Production', skills: ['Video Editing', 'Animation', 'Voiceover', 'Premiere Pro'], status: 'open', employer_id: 'e10', location: 'Nehru Place, Delhi', createdAt: '2026-01-24T10:00:00Z', updatedAt: '2026-01-24T10:00:00Z' },
  { id: 'g11', title: 'Resume Writing (10 Resumes)', description: 'Write professional resumes for job seekers. Include keyword optimization for ATS.', budget: 8000, category: 'Writing', skills: ['Resume Writing', 'Copywriting', 'ATS Optimization'], status: 'open', employer_id: 'e11', location: 'Rohini, Delhi', createdAt: '2026-01-26T10:00:00Z', updatedAt: '2026-01-26T10:00:00Z' },
  { id: 'g12', title: 'Android App Bug Fixes', description: 'Fix 15 bugs in an existing Android app. API integration issues and UI glitches.', budget: 12000, category: 'Mobile Development', skills: ['Android', 'Java', 'Kotlin', 'REST APIs'], status: 'open', employer_id: 'e12', location: 'Noida Sector 15', createdAt: '2026-01-28T10:00:00Z', updatedAt: '2026-01-28T10:00:00Z' },
  { id: 'g13', title: 'Book Cover Design', description: 'Design a professional book cover for a self-help book. Provide 3 concept options.', budget: 4000, category: 'Graphic Design', skills: ['Cover Design', 'Illustrator', 'Print Design'], status: 'open', employer_id: 'e13', location: 'Greater Kailash, Delhi', createdAt: '2026-01-30T10:00:00Z', updatedAt: '2026-01-30T10:00:00Z' },
  { id: 'g14', title: 'Excel Dashboard Creation', description: 'Create an interactive Excel dashboard with pivot tables, charts, and data visualization.', budget: 6000, category: 'Data Analysis', skills: ['Excel', 'Pivot Tables', 'Charts', 'Data Visualization'], status: 'open', employer_id: 'e14', location: 'Karol Bagh, Delhi', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: 'g15', title: 'Email Marketing Setup', description: 'Set up email campaigns in Mailchimp. Design templates and set up automation flows.', budget: 7000, category: 'Digital Marketing', skills: ['Mailchimp', 'Email Marketing', 'HTML Email', 'Automation'], status: 'open', employer_id: 'e15', location: 'Janakpuri, Delhi', createdAt: '2026-02-03T10:00:00Z', updatedAt: '2026-02-03T10:00:00Z' },
  { id: 'g16', title: 'Virtual Assistant (20 hrs/month)', description: 'Handle administrative tasks: email management, calendar, data entry, and research.', budget: 15000, category: 'Admin Support', skills: ['Admin Support', 'Email Management', 'Research', 'Data Entry'], status: 'open', employer_id: 'e16', location: 'Lajpat Nagar, Delhi', createdAt: '2026-02-05T10:00:00Z', updatedAt: '2026-02-05T10:00:00Z' },
  { id: 'g17', title: '3D Product Modeling', description: 'Create 3D models of furniture products for an e-commerce catalog. 20 items needed.', budget: 20000, category: '3D Design', skills: ['3D Modeling', 'Blender', 'Product Visualization', 'Rendering'], status: 'open', employer_id: 'e17', location: 'Faridabad Sector 15', createdAt: '2026-02-07T10:00:00Z', updatedAt: '2026-02-07T10:00:00Z' },
  { id: 'g18', title: 'Podcast Editing (10 Episodes)', description: 'Edit and produce podcast episodes. Remove filler words, add intros/outros, and normalize audio.', budget: 10000, category: 'Audio Production', skills: ['Audio Editing', 'Audacity', 'Podcast Production', 'Sound Design'], status: 'open', employer_id: 'e18', location: 'Vasant Kunj, Delhi', createdAt: '2026-02-09T10:00:00Z', updatedAt: '2026-02-09T10:00:00Z' },
  { id: 'g19', title: ' Shopify Store Setup', description: 'Set up a complete Shopify store with theme customization, apps, and payment integration.', budget: 15000, category: 'E-commerce', skills: ['Shopify', 'Liquid', 'E-commerce', 'Payment Integration'], status: 'open', employer_id: 'e19', location: 'Gurgaon Golf Course', createdAt: '2026-02-11T10:00:00Z', updatedAt: '2026-02-11T10:00:00Z' },
  { id: 'g20', title: 'Translation (English to Hindi)', description: 'Translate 50 product descriptions from English to Hindi. Maintain tone and readability.', budget: 5000, category: 'Translation', skills: ['Translation', 'English', 'Hindi', 'Content Writing'], status: 'open', employer_id: 'e20', location: 'Pitampura, Delhi', createdAt: '2026-02-13T10:00:00Z', updatedAt: '2026-02-13T10:00:00Z' },
  { id: 'g21', title: 'Facebook Ads Campaign', description: 'Set up and manage Facebook/Instagram ad campaigns for a local restaurant. Target local audience.', budget: 8000, category: 'Digital Marketing', skills: ['Facebook Ads', 'Instagram Ads', 'Targeting', 'Analytics'], status: 'open', employer_id: 'e21', location: 'Defence Colony, Delhi', createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-02-15T10:00:00Z' },
  { id: 'g22', title: 'Database Migration', description: 'Migrate data from MySQL to PostgreSQL. Maintain data integrity and fix any compatibility issues.', budget: 12000, category: 'Database', skills: ['MySQL', 'PostgreSQL', 'Data Migration', 'SQL'], status: 'open', employer_id: 'e22', location: 'Noida Sector 62', createdAt: '2026-02-17T10:00:00Z', updatedAt: '2026-02-17T10:00:00Z' },
  { id: 'g23', title: 'Illustrations for Children\'s Book', description: 'Create 20 colorful illustrations for a children storybook. Cartoon style, age group 5-8 years.', budget: 25000, category: 'Illustration', skills: ['Illustration', 'Children Book', 'Digital Art', 'Cartoon'], status: 'open', employer_id: 'e23', location: 'Green Park, Delhi', createdAt: '2026-02-19T10:00:00Z', updatedAt: '2026-02-19T10:00:00Z' },
  { id: 'g24', title: 'WordPress Malware Removal', description: 'Clean malware from 3 WordPress sites. Remove malicious code and implement security measures.', budget: 6000, category: 'Web Security', skills: ['WordPress', 'PHP', 'Security', 'Malware Removal'], status: 'open', employer_id: 'e24', location: 'Connaught Place, Delhi', createdAt: '2026-02-21T10:00:00Z', updatedAt: '2026-02-21T10:00:00Z' },
  { id: 'g25', title: 'Google My Business Setup', description: 'Set up and optimize Google My Business listings for 5 local businesses. Include photos and posts.', budget: 4000, category: 'Local SEO', skills: ['Google My Business', 'Local SEO', 'Online Presence'], status: 'open', employer_id: 'e25', location: 'Rajouri Garden, Delhi', createdAt: '2026-02-23T10:00:00Z', updatedAt: '2026-02-23T10:00:00Z' },
  { id: 'g26', title: 'PowerPoint Presentation', description: 'Create a professional 20-slide investor pitch deck. Modern design with data visualizations.', budget: 5000, category: 'Presentation', skills: ['PowerPoint', 'Presentation Design', 'Data Visualization'], status: 'open', employer_id: 'e26', location: 'Gurgaon Cyber City', createdAt: '2026-02-25T10:00:00Z', updatedAt: '2026-02-25T10:00:00Z' },
  { id: 'g27', title: 'Wireframe Design', description: 'Create wireframes for a healthcare app. Include all screens: onboarding, dashboard, booking, etc.', budget: 8000, category: 'UI/UX Design', skills: ['Wireframing', 'Figma', 'UX Design', 'App Design'], status: 'open', employer_id: 'e27', location: 'Saket, Delhi', createdAt: '2026-02-27T10:00:00Z', updatedAt: '2026-02-27T10:00:00Z' },
  { id: 'g28', title: 'Python Script Automation', description: 'Write Python scripts to automate Excel file processing and generate reports daily.', budget: 7000, category: 'Automation', skills: ['Python', 'Automation', 'Excel', 'Scripting'], status: 'open', employer_id: 'e28', location: 'Dwarka, Delhi', createdAt: '2026-03-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: 'g29', title: 'Music Composition (Background)', description: 'Compose 5 original background tracks for YouTube videos. royalty-free.', budget: 10000, category: 'Music Production', skills: ['Music Composition', 'Audio Production', 'DAW', 'Royalty-Free'], status: 'open', employer_id: 'e29', location: 'Hauz Khas, Delhi', createdAt: '2026-03-03T10:00:00Z', updatedAt: '2026-03-03T10:00:00Z' },
  { id: 'g30', title: 'Survey Data Analysis', description: 'Analyze survey data from 500 respondents. Create charts, identify trends, and write insights.', budget: 5000, category: 'Data Analysis', skills: ['Data Analysis', 'Statistics', 'Excel', 'Report Writing'], status: 'open', employer_id: 'e30', location: 'Noida Sector 15', createdAt: '2026-03-05T10:00:00Z', updatedAt: '2026-03-05T10:00:00Z' },
]

export const dummyReviews = [
  { id: 'r1', booking_id: 'b1', service_id: 's1', customer_id: 'c1', worker_id: 'w2', customer_name: 'Priya Sharma', service_title: 'Professional Home Cleaning', service_type: 'Home Cleaning', rating: 5, comment: 'Absolutely spotless! Priya did an amazing job with the deep cleaning. My apartment looks brand new. Highly recommended!', tags: ['Professional', 'On Time', 'Great Value'], createdAt: '2026-01-18T10:00:00Z' },
  { id: 'r2', booking_id: 'b2', service_id: 's2', customer_id: 'c2', worker_id: 'w1', customer_name: 'Rahul Mehta', service_title: 'Plumbing & Pipe Repair', service_type: 'Plumber', rating: 5, comment: 'Rajesh fixed a major leak in under an hour. Very professional and explained everything clearly. Fair pricing too.', tags: ['Expert', 'Quick Service'], createdAt: '2026-01-16T10:00:00Z' },
  { id: 'r3', booking_id: 'b3', service_id: 's3', customer_id: 'c3', worker_id: 'w3', customer_name: 'Anita Desai', service_title: 'Electrical Wiring & Repair', service_type: 'Electrician', rating: 5, comment: 'Got my entire house rewired. Amar and his team were incredibly thorough and safety-conscious. Excellent work!', tags: ['Professional', 'Safety First', 'Thorough'], createdAt: '2026-01-14T10:00:00Z' },
  { id: 'r4', booking_id: 'b4', service_id: 's4', customer_id: 'c4', worker_id: 'w4', customer_name: 'Deepak Verma', service_title: 'Interior & Exterior Painting', service_type: 'Painter', rating: 4, comment: 'Good painting work overall. The texture finish on the accent wall looks beautiful. Took a bit longer than expected but worth it.', tags: ['Good Quality', 'Creative'], createdAt: '2026-01-12T10:00:00Z' },
  { id: 'r5', booking_id: 'b5', service_id: 's5', customer_id: 'c5', worker_id: 'w5', customer_name: 'Sneha Iyer', service_title: 'Custom Furniture & Carpentry', service_type: 'Carpenter', rating: 5, comment: 'Vikram built a custom bookshelf and study table for my home office. The craftsmanship is outstanding. Will definitely hire again.', tags: ['Skilled', 'Creative', 'Professional'], createdAt: '2026-01-10T10:00:00Z' },
  { id: 'r6', booking_id: 'b6', service_id: 's6', customer_id: 'c6', worker_id: 'w6', customer_name: 'Amit Tiwari', service_title: 'Housekeeping & Gardening', service_type: 'Housekeeping', rating: 5, comment: 'My terrace garden looks magical! Meena has a great eye for design and chose the perfect plants for the space.', tags: ['Creative', 'Great Value', 'On Time'], createdAt: '2026-01-08T10:00:00Z' },
  { id: 'r7', booking_id: 'b7', service_id: 's7', customer_id: 'c7', worker_id: 'w7', customer_name: 'Nisha Kapoor', service_title: 'AC Installation & Repair', service_type: 'AC Repair', rating: 5, comment: 'Arjun was extremely knowledgeable. He diagnosed the AC issue quickly and the repair cost was very reasonable. Cooling is perfect now!', tags: ['Expert', 'Affordable', 'Quick Service'], createdAt: '2026-01-06T10:00:00Z' },
  { id: 'r8', booking_id: 'b8', service_id: 's8', customer_id: 'c8', worker_id: 'w8', customer_name: 'Meera Jain', service_title: 'Salon & Beauty at Home', service_type: 'Salon at Home', rating: 5, comment: 'Fatima did my bridal makeup and it was absolutely stunning! She is so talented and patient. All my guests were impressed.', tags: ['Talented', 'Patient', 'Professional'], createdAt: '2026-01-04T10:00:00Z' },
]

export const dummyBookings = [
  { id: 'bk1', service_title: 'Professional Home Cleaning', customer_name: 'Priya Sharma', worker_name: 'Priya Singh', customer_id: 'c1', worker_id: 'w2', booking_date: '2026-01-20', time_slot: '9:00 AM - 11:00 AM', amount: 1500, status: 'completed', payment_status: 'paid', address: 'B-12, Connaught Place, New Delhi', createdAt: '2026-01-18T10:00:00Z' },
  { id: 'bk2', service_title: 'Plumbing & Pipe Repair', customer_name: 'Rahul Mehta', worker_name: 'Rajesh Kumar', customer_id: 'c2', worker_id: 'w1', booking_date: '2026-01-22', time_slot: '11:00 AM - 1:00 PM', amount: 800, status: 'completed', payment_status: 'paid', address: '45, Lajpat Nagar II, New Delhi', createdAt: '2026-01-20T10:00:00Z' },
  { id: 'bk3', service_title: 'AC Installation & Repair', customer_name: 'Nisha Kapoor', worker_name: 'Arjun Reddy', customer_id: 'c7', worker_id: 'w7', booking_date: '2026-01-25', time_slot: '2:00 PM - 4:00 PM', amount: 1800, status: 'accepted', payment_status: 'pending', address: 'C-88, Saket, New Delhi', createdAt: '2026-01-22T10:00:00Z' },
  { id: 'bk4', service_title: 'Salon & Beauty at Home', customer_name: 'Meera Jain', worker_name: 'Fatima Khan', customer_id: 'c8', worker_id: 'w8', booking_date: '2026-01-28', time_slot: '9:00 AM - 11:00 AM', amount: 1500, status: 'on_the_way', payment_status: 'paid', address: '23, Khan Market, New Delhi', createdAt: '2026-01-25T10:00:00Z' },
  { id: 'bk5', service_title: 'Pest Control Treatment', customer_name: 'Deepak Verma', worker_name: 'Kavitha Nair', customer_id: 'c4', worker_id: 'w10', booking_date: '2026-02-01', time_slot: '11:00 AM - 1:00 PM', amount: 2500, status: 'requested', payment_status: 'pending', address: 'A-67, Defence Colony, New Delhi', createdAt: '2026-01-28T10:00:00Z' },
  { id: 'bk6', service_title: 'Mobile Phone Repair', customer_name: 'Sneha Iyer', worker_name: 'Rohit Sharma', customer_id: 'c5', worker_id: 'w11', booking_date: '2026-02-03', time_slot: '2:00 PM - 4:00 PM', amount: 500, status: 'cancelled', payment_status: 'refunded', address: '34, Chandni Chowk, Old Delhi', createdAt: '2026-01-30T10:00:00Z' },
]

export const dummyUsers = [
  { id: 'c1', name: 'Priya Sharma', email: 'priya.sharma@example.com', user_type: 'customer', location: 'Connaught Place, Delhi', phone: '+91 91234 56701', suspended: false, createdAt: '2025-11-01T10:00:00Z' },
  { id: 'c2', name: 'Rahul Mehta', email: 'rahul.mehta@example.com', user_type: 'customer', location: 'Lajpat Nagar, Delhi', phone: '+91 91234 56702', suspended: false, createdAt: '2025-11-05T10:00:00Z' },
  { id: 'c3', name: 'Anita Desai', email: 'anita.desai@example.com', user_type: 'customer', location: 'Karol Bagh, Delhi', phone: '+91 91234 56703', suspended: false, createdAt: '2025-11-10T10:00:00Z' },
  { id: 'c4', name: 'Deepak Verma', email: 'deepak.verma@example.com', user_type: 'customer', location: 'Defence Colony, Delhi', phone: '+91 91234 56704', suspended: false, createdAt: '2025-11-15T10:00:00Z' },
  { id: 'c5', name: 'Sneha Iyer', email: 'sneha.iyer@example.com', user_type: 'customer', location: 'Dwarka, Delhi', phone: '+91 91234 56705', suspended: false, createdAt: '2025-11-20T10:00:00Z' },
  { id: 'w1', name: 'Rajesh Kumar', email: 'rajesh@example.com', user_type: 'worker', location: 'Lajpat Nagar, Delhi', phone: '+91 98765 43210', suspended: false, createdAt: '2025-10-01T10:00:00Z' },
  { id: 'w2', name: 'Priya Singh', email: 'priya@example.com', user_type: 'worker', location: 'Connaught Place, Delhi', phone: '+91 98765 43211', suspended: false, createdAt: '2025-10-05T10:00:00Z' },
  { id: 'w3', name: 'Amar Patel', email: 'amar@example.com', user_type: 'worker', location: 'Karol Bagh, Delhi', phone: '+91 98765 43212', suspended: false, createdAt: '2025-10-10T10:00:00Z' },
  { id: 'e1', name: 'TechVista HR', email: 'hr@techvista.com', user_type: 'employer', location: 'Connaught Place, Delhi', phone: '+91 11 4000 1001', suspended: false, createdAt: '2025-09-01T10:00:00Z' },
  { id: 'e2', name: 'DesignCraft HR', email: 'hr@designcraft.com', user_type: 'employer', location: 'Hauz Khas, Delhi', phone: '+91 11 4000 1002', suspended: false, createdAt: '2025-09-05T10:00:00Z' },
]

export const TIME_SLOTS = [
  { id: 'slot-1', label: '9:00 AM - 11:00 AM', value: '9:00 AM - 11:00 AM' },
  { id: 'slot-2', label: '11:00 AM - 1:00 PM', value: '11:00 AM - 1:00 PM' },
  { id: 'slot-3', label: '2:00 PM - 4:00 PM', value: '2:00 PM - 4:00 PM' },
]

export const BOOKING_STATUSES = [
  { key: 'requested', label: 'Requested', color: 'bg-yellow-100 text-yellow-800' },
  { key: 'accepted', label: 'Accepted', color: 'bg-blue-100 text-blue-800' },
  { key: 'on_the_way', label: 'On the Way', color: 'bg-indigo-100 text-indigo-800' },
  { key: 'completed', label: 'Completed', color: 'bg-green-100 text-green-800' },
  { key: 'reviewed', label: 'Reviewed', color: 'bg-emerald-100 text-emerald-800' },
  { key: 'cancelled', label: 'Cancelled', color: 'bg-red-100 text-red-800' },
]

export function calculateWorkerScore(worker, maxDistance = 15) {
  const rating = worker.rating || 0
  const experience = worker.experience_years || 0
  const distance = worker.distance || maxDistance
  const completionRate = worker.completion_rate || 100

  const ratingScore = (rating / 5.0) * 0.35 * 100
  const experienceScore = Math.min(experience / 10.0, 1.0) * 0.25 * 100
  const distanceScore = (1 - Math.min(distance / maxDistance, 1.0)) * 0.20 * 100
  const completionScore = (completionRate / 100.0) * 0.20 * 100

  return Math.round((ratingScore + experienceScore + distanceScore + completionScore) * 100) / 100
}

export function formatCurrencyINR(amount) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatSalaryRange(min, max) {
  const fmt = v => {
    if (v >= 100000) return `${(v / 100000).toFixed(v % 100000 === 0 ? 0 : 1)}L`
    if (v >= 1000) return `${(v / 1000).toFixed(0)}K`
    return `${v}`
  }
  return `${fmt(min)} - ${fmt(max)} /yr`
}
